baseurl = "https://example.com/"
title = "Site Title"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[params]
    author = "Cat Behaviourist"
    avatar = "miu_logo.jpg"
    favicon = "favicon.ico"
    description = """
        Coming soon.
        Veterinary specialist in Cat Behaviour.
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fab fa-medium'></i>" #Choose your favorite font from Font Awesome #pre = "<i class='fab fa-medium'></i>"
    url = "https://medium.com/@catvetguide"
    weight = 20
    
[[menu.main]]
    identifier = "instagram"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fab fa-instagram'></i>" #Choose your favorite font from Font Awesome #pre = "<i class='fab fa-medium'></i>"
    url = "https://www.instagram.com/cat_guide/"
    weight = 10
